import { writeFileSync, mkdirSync, existsSync, chmodSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

interface ZeroClawConfig {
  apiKey: string;
  provider: string;
  model: string;
  telegramBotToken?: string;
  telegramAllowedUsers?: string[];
  memoryBackend: string;
  postgresUrl?: string;
  autonomyLevel: string;
  allowedCommands: string[];
  gatewayPort: number;
  workspaceDir: string;
}

function buildToml(cfg: ZeroClawConfig): string {
  const lines: string[] = [
    `# Auto-generated by claw-infra reporter — do not edit manually`,
    `api_key = "${cfg.apiKey}"`,
    `default_provider = "${cfg.provider}"`,
    `default_model = "${cfg.model}"`,
    `default_temperature = 0.7`,
    '',
    '[memory]',
    `backend = "${cfg.memoryBackend}"`,
    'auto_save = true',
  ];

  if (cfg.memoryBackend === 'postgres' && cfg.postgresUrl) {
    lines.push('');
    lines.push('[storage.provider.config]');
    lines.push('provider = "postgres"');
    lines.push(`db_url = "${cfg.postgresUrl}"`);
  }

  lines.push('');
  lines.push('[gateway]');
  lines.push(`port = ${cfg.gatewayPort}`);
  lines.push('host = "0.0.0.0"');
  lines.push('require_pairing = false');
  lines.push('allow_public_bind = true');

  lines.push('');
  lines.push('[autonomy]');
  lines.push(`level = "${cfg.autonomyLevel}"`);
  lines.push('workspace_only = true');
  const cmds = cfg.allowedCommands.map((c) => `"${c}"`).join(', ');
  lines.push(`allowed_commands = [${cmds}]`);
  lines.push('max_actions_per_hour = 120');
  // Required by newer ZeroClaw config schema.
  lines.push('forbidden_paths = [');
  lines.push('  "/etc",');
  lines.push('  "/bin",');
  lines.push('  "/sbin",');
  lines.push('  "/usr/bin",');
  lines.push('  "/usr/sbin",');
  lines.push('  "/root/.ssh",');
  lines.push('  "/proc",');
  lines.push('  "/sys",');
  lines.push('  "/dev"');
  lines.push(']');

  lines.push('');
  lines.push('[runtime]');
  lines.push('kind = "native"');

  lines.push('');
  lines.push('[tunnel]');
  lines.push('provider = "none"');

  lines.push('');
  lines.push('[secrets]');
  lines.push('encrypt = true');

  if (cfg.telegramBotToken) {
    lines.push('');
    lines.push('[channels_config.telegram]');
    lines.push(`bot_token = "${cfg.telegramBotToken}"`);
    if (cfg.telegramAllowedUsers?.length) {
      const users = cfg.telegramAllowedUsers.map((u) => `"${u}"`).join(', ');
      lines.push(`allowed_users = [${users}]`);
    } else {
      lines.push('allowed_users = []');
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function generateConfig(): string {
  const apiKey = process.env.ZEROCLAW_API_KEY || process.env.OPENROUTER_API_KEY || '';
  if (!apiKey) {
    console.warn('[config-gen] WARNING: No API key found (ZEROCLAW_API_KEY or OPENROUTER_API_KEY)');
  }

  const cfg: ZeroClawConfig = {
    apiKey,
    provider: process.env.ZEROCLAW_PROVIDER || 'openrouter',
    model: process.env.ZEROCLAW_MODEL || 'anthropic/claude-sonnet-4-6',
    telegramBotToken: process.env.ZEROCLAW_TELEGRAM_BOT_TOKEN,
    telegramAllowedUsers: process.env.ZEROCLAW_TELEGRAM_ALLOWED_USERS?.split(',').map((s) => s.trim()).filter(Boolean),
    memoryBackend: process.env.ZEROCLAW_MEMORY_BACKEND || 'postgres',
    postgresUrl: process.env.DATABASE_URL,
    autonomyLevel: process.env.ZEROCLAW_AUTONOMY || 'supervised',
    allowedCommands: (process.env.ZEROCLAW_ALLOWED_COMMANDS || 'git,npm,cargo,ls,cat,grep,curl').split(',').map((s) => s.trim()),
    gatewayPort: parseInt(process.env.ZEROCLAW_GATEWAY_PORT || '3002', 10),
    workspaceDir: process.env.ZEROCLAW_WORKSPACE || '/app/workspace',
  };

  if (cfg.memoryBackend === 'postgres' && !cfg.postgresUrl) {
    throw new Error('[config-gen] ZEROCLAW_MEMORY_BACKEND=postgres requires DATABASE_URL');
  }

  const toml = buildToml(cfg);

  // ZeroClaw may resolve config relative to HOME or process cwd depending on runtime.
  // Write to both common locations so container startups are deterministic.
  const candidateDirs = [
    join(homedir(), '.zeroclaw'),
    '/app/.zeroclaw',
  ];

  let primaryPath = '';
  for (const dir of candidateDirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    const path = join(dir, 'config.toml');
    writeFileSync(path, toml, 'utf-8');
    // Avoid noisy warning from ZeroClaw about world-readable config.
    chmodSync(path, 0o600);
    if (!primaryPath) primaryPath = path;
    console.log(`[config-gen] Wrote ZeroClaw config to ${path}`);
  }
  console.log(`[config-gen] Provider: ${cfg.provider}, Model: ${cfg.model}`);
  console.log(`[config-gen] Memory: ${cfg.memoryBackend}, Autonomy: ${cfg.autonomyLevel}`);
  console.log(`[config-gen] Telegram: ${cfg.telegramBotToken ? 'enabled' : 'disabled'}`);

  return primaryPath;
}

if (require.main === module) {
  generateConfig();
}
