import { writeFileSync, mkdirSync, existsSync, chmodSync } from 'fs';
import { homedir, platform } from 'os';
import { join } from 'path';
import { execSync } from 'child_process';

interface ZeroClawConfig {
  apiKey: string;
  provider: string;
  model: string;
  telegramBotToken?: string;
  telegramAllowedUsers?: string[];
  memoryBackend: string;
  postgresUrl?: string;
  autonomyLevel: string;
  allowedCommands: string[];
  gatewayPort: number;
  workspaceDir: string;
  githubToken?: string;
}

function buildToml(cfg: ZeroClawConfig): string {
  const cmds = cfg.allowedCommands.map((c) => `"${c}"`).join(', ');

  const sections: string[] = [
    `# Auto-generated by claw-infra reporter — do not edit manually`,
    `api_key = "${cfg.apiKey}"`,
    `default_provider = "${cfg.provider}"`,
    `default_model = "${cfg.model}"`,
    `default_temperature = 0.7`,

    ``,
    `[memory]`,
    `backend = "${cfg.memoryBackend}"`,
    `auto_save = true`,

    ``,
    `[gateway]`,
    `port = ${cfg.gatewayPort}`,
    `host = "0.0.0.0"`,
    `require_pairing = false`,
    `allow_public_bind = true`,

    ``,
    `[autonomy]`,
    `level = "${cfg.autonomyLevel}"`,
    `workspace_only = false`,
    `allowed_commands = [${cmds}]`,
    `allowed_roots = ["${cfg.workspaceDir}", "/app/workspace", "/tmp"]`,
    `max_actions_per_hour = 200`,
    `max_cost_per_day_cents = 5000`,
    `max_iterations = 100`,
    `max_tool_calls = 100`,
    `require_approval_for_medium_risk = false`,
    `block_high_risk_commands = false`,
    `auto_approve = ["shell", "file_read", "file_write", "file_edit"]`,
    `always_ask = []`,
    `forbidden_paths = ["/etc/shadow", "/etc/passwd", "/root/.ssh", "/proc", "/sys", "/dev"]`,

    ``,
    `[observability]`,
    `backend = "log"`,
    `runtime_trace_mode = "rolling"`,
    `runtime_trace_max_entries = 200`,

    ``,
    `[runtime]`,
    `kind = "native"`,

    ``,
    `[tunnel]`,
    `provider = "none"`,

    ``,
    `[secrets]`,
    `encrypt = true`,
  ];

  if (cfg.memoryBackend === 'postgres' && cfg.postgresUrl) {
    sections.push(``, `[storage.provider.config]`, `provider = "postgres"`, `db_url = "${cfg.postgresUrl}"`);
  }

  // channels_config.cli is a required field in the channels_config struct.
  sections.push(``, `[channels_config]`, `cli = true`);

  if (cfg.telegramBotToken) {
    sections.push(``, `[channels_config.telegram]`, `bot_token = "${cfg.telegramBotToken}"`);
    if (cfg.telegramAllowedUsers?.length) {
      const users = cfg.telegramAllowedUsers.map((u) => `"${u}"`).join(', ');
      sections.push(`allowed_users = [${users}]`);
    } else {
      sections.push(`allowed_users = []`);
    }
  }

  sections.push(``);
  return sections.join('\n');
}

export function generateConfig(): string {
  const apiKey = process.env.ZEROCLAW_API_KEY || process.env.OPENROUTER_API_KEY || '';
  if (!apiKey) {
    console.warn('[config-gen] WARNING: No API key found (ZEROCLAW_API_KEY or OPENROUTER_API_KEY)');
  }

  const cfg: ZeroClawConfig = {
    apiKey,
    provider: process.env.ZEROCLAW_PROVIDER || 'openrouter',
    model: process.env.ZEROCLAW_MODEL || 'anthropic/claude-sonnet-4-6',
    telegramBotToken: process.env.ZEROCLAW_TELEGRAM_BOT_TOKEN,
    telegramAllowedUsers: process.env.ZEROCLAW_TELEGRAM_ALLOWED_USERS?.split(',').map((s) => s.trim()).filter(Boolean),
    memoryBackend: process.env.ZEROCLAW_MEMORY_BACKEND || 'sqlite',
    postgresUrl: process.env.DATABASE_URL,
    autonomyLevel: process.env.ZEROCLAW_AUTONOMY || 'supervised',
    allowedCommands: (process.env.ZEROCLAW_ALLOWED_COMMANDS || 'git,npm,npx,cargo,ls,cat,grep,curl,wget,find,head,tail,wc,diff,sort,uniq,mkdir,cp,mv,rm,touch,echo,sed,awk,tar,unzip,python3,node,sh,bash').split(',').map((s) => s.trim()),
    gatewayPort: parseInt(process.env.ZEROCLAW_GATEWAY_PORT || '3002', 10),
    workspaceDir: process.env.ZEROCLAW_WORKSPACE || '/app/workspace',
    githubToken: process.env.GITHUB_TOKEN || process.env.ZEROCLAW_GITHUB_TOKEN,
  };

  if (cfg.memoryBackend === 'postgres' && !cfg.postgresUrl) {
    throw new Error('[config-gen] ZEROCLAW_MEMORY_BACKEND=postgres requires DATABASE_URL');
  }

  const toml = buildToml(cfg);

  // ZeroClaw may resolve config relative to HOME or process cwd depending on runtime.
  // Write to both common locations so container startups are deterministic.
  const candidateDirs = [
    join(homedir(), '.zeroclaw'),
    '/app/.zeroclaw',
  ];

  let primaryPath = '';
  for (const dir of candidateDirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    const path = join(dir, 'config.toml');
    writeFileSync(path, toml, 'utf-8');
    // Avoid noisy warning from ZeroClaw about world-readable config.
    chmodSync(path, 0o600);
    if (!primaryPath) primaryPath = path;
    console.log(`[config-gen] Wrote ZeroClaw config to ${path}`);
  }
  console.log(`[config-gen] Provider: ${cfg.provider}, Model: ${cfg.model}`);
  console.log(`[config-gen] Memory: ${cfg.memoryBackend}, Autonomy: ${cfg.autonomyLevel}`);
  console.log(`[config-gen] Telegram: ${cfg.telegramBotToken ? 'enabled' : 'disabled'}`);

  // ── GitHub credential helper ──
  // Configure git to authenticate with GITHUB_TOKEN so the agent can clone
  // private repos and view repository contents via the GitHub API.
  if (cfg.githubToken && platform() !== 'win32') {
    try {
      // Write a minimal credential helper script
      const helperPath = '/usr/local/bin/git-credentials-github';
      const helperScript = `#!/bin/sh\necho "username=x-access-token"\necho "password=${cfg.githubToken}"\n`;
      writeFileSync(helperPath, helperScript, 'utf-8');
      chmodSync(helperPath, 0o755);

      // Point git at the helper for github.com
      execSync('git config --global credential.https://github.com.helper /usr/local/bin/git-credentials-github', { stdio: 'pipe' });

      // Also set a token-based URL rewrite so "git clone https://" works without a prompt
      execSync(`git config --global url."https://x-access-token:${cfg.githubToken}@github.com/".insteadOf "https://github.com/"`, { stdio: 'pipe' });

      // Configure git identity so commits don't fail (default no-op identity)
      const gitName = process.env.GIT_AUTHOR_NAME || 'zeroclaw-agent';
      const gitEmail = process.env.GIT_AUTHOR_EMAIL || 'agent@zeroclaw.local';
      execSync(`git config --global user.name "${gitName}"`, { stdio: 'pipe' });
      execSync(`git config --global user.email "${gitEmail}"`, { stdio: 'pipe' });

      console.log('[config-gen] GitHub credential helper configured (GITHUB_TOKEN)');
    } catch (err) {
      console.warn('[config-gen] WARNING: Failed to configure GitHub credential helper:', err);
    }
  } else if (!cfg.githubToken) {
    console.warn('[config-gen] No GITHUB_TOKEN set — agent will not be able to access private GitHub repos.');
  }

  return primaryPath;
}

if (require.main === module) {
  generateConfig();
}
